name: Test HDF5 REST VOL

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout vol-tests
      uses: actions/checkout@v3
    - name: Checkout HDF5
      uses: actions/checkout@v3
      with:
        repository: HDFGroup/hdf5
        path: hdf5    
    - name: Checkout REST VOL
      uses: actions/checkout@v3
      with:
        repository: HDFGroup/vol-rest
        path: vol-rest
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install ninja-build automake autoconf libtool libtool-bin libopenmpi-dev
        sudo apt-get update -y	
        sudo apt-get install -y libyajl-dev libcurl4-openssl-dev
    - name: Install HDF5
      run: |
        mkdir hdf5/build
        cd hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_THREADSAFE:BOOL=ON -DALLOW_UNSUPPORTED:BOOL=ON ..        
        sudo make -j install
        cd ..
        git rev-parse HEAD > git.txt
    - name: Install REST VOL
      run: |
        mkdir vol-rest/build
        cd vol-rest/build
        cmake ..
        make
        ctest
